# Generated by Django 2.1.5 on 2020-02-08 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200208_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='friend',
            name='friend_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='api.Student'),
        ),
        migrations.AddField(
            model_name='friend',
            name='my_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to='api.Student'),
        ),
    ]
