# Generated by Django 2.1.5 on 2020-02-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200208_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_shop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_shop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=0),
        ),
    ]
