# Generated by Django 2.1.5 on 2020-02-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200208_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
